#tomcat port
server:
  port: 8080
  ssl:
    enabled: true
    key-alias: staykeystore
    key-store: staykeystore.pkcs12
    key-store-password: 'sist1234'
    key-password: 'sist1234'
    trust-store: staytrust.pkcs12
    trust-store-password: 'sist1234'

#jsp
spring:
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
  devtools:
    livereload:
      enabled: true
      
  #mail    
  mail:
   host: smtp.gmail.com
   port: 587
   username: staySwim@gmail.com
   password: stay1234!
   properties:
    mail:
        smtp:
          auth: true
          starttls:
            enable: true
      
  #mysql
#  db-mysql:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://sist-stay.ct5m6xbkyvuw.ap-northeast-2.rds.amazonaws.com:3306/stay?serverTimezone=Asia/Seoul
    username: admin
    password: sist1234
      
#mybatis
mybatis:
  type-aliases-package: stay.data.mapper, stay.data.dto
  mapper-locations:
  - /mapper/**/*.xml
  
   